### ISSUE TITLE
Moderate Command

### ISSUE THREAD

**Issue by iGetUploaded** [Hallel9/Communitea#1]
Hello, I recently saw you posted a **_All-in-one Moderation Command_**  on discord and I'm trying to use it but I keep getting weird errors. One error is _if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');_   

which then says this Error _[INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred._ 
It's prob just some weird error I'm overseeing and not noticing it

**Comment by Hallel9** [comment]
Okay. What server are you from?

**Comment by iGetUploaded** [comment]
Im in Recon dev server

**Comment by Hallel9** [comment]
Ping me in a help channel with the message “Can you help me with your moderate command?”

**Comment by Hallel9** [comment]
Hallel is my username

**Comment by iGetUploaded** [comment]
Okay will do
